# Generated by Django 5.2.8 on 2025-11-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0002_remove_movie_rating_comment_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
