# Generated by Django 5.2.8 on 2025-11-24 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
