# Generated by Django 5.2.8 on 2025-11-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
