# Generated by Django 5.2.8 on 2025-11-26 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0011_movie_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='scores_count',
        ),
    ]
