# Generated by Django 5.2.8 on 2025-11-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0012_remove_movie_scores_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='movies', to='kino.genre'),
        ),
    ]
